spring.application.name=HoneyQBE
spring.datasource.url=jdbc:postgresql://localhost:5432/yourdb
spring.datasource.username=dbuser
spring.datasource.password=dbpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
user.security.defaultAction=deny
user.security.bcryptStrength=12
user.security.failedLoginAttempts=5
user.security.accountLockoutDuration=15
user.registration.sendVerificationEmail=false
