spring.application.name=HoneyQBE
spring.config.import=secrets.properties

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/honeyq
spring.datasource.username=${postgres.username}
spring.datasource.password=${postgres.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Essential Security OAuth2 Framework Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8081/realms/master
