spring.application.name=HoneyQBE
spring.config.import=secrets.properties

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:32768/honeyq
spring.datasource.username=${postgres.username}
spring.datasource.password=${postgres.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Essential Security OAuth2 Framework Configuration
# spring.security.oauth2.client.registration.facebook.client-id=${facebook.client-id}
# spring.security.oauth2.client.registration.facebook.client-secret=${facebook.client-secret}

# spring.security.oauth2.client.registration.google.client-id=${google.client-id}
# spring.security.oauth2.client.registration.google.client-secret=${google.client-secret}

