spring.application.name=HoneyQBE
spring.config.import=secrets.properties
spring.web.error.include-message=always

# PostgreSQL
spring.datasource.url=jdbc:postgresql://172.18.0.8:5432/honeyq
spring.datasource.username=${postgres-production.username}
spring.datasource.password=${postgres-production.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Essential Security OAuth2 Framework Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri: https://auth.honeyq.be/realms/honeyq
honeyq.keycloak-base-url=https://auth.honeyq.be
honeyq.keycloak-validated-user-role-id=c470cc86-ad26-47c0-ac8c-d8b7206b054c


## BELANGRIJk!!!!! ook de cors policy aanpassen !!!!!!!!!!!!!!!!!!!!!